# Problem Statement: Linear Programming Optimization

## Objective
**Maximize** the objective function:
$$Z = x_1 + 3x_2$$

## Constraints
Subject to the following linear inequalities:
1.  $-x_1 + x_2 \leq 3$
2.  $-x_1 + 2x_2 \leq 8$
3.  $3x_1 + x_2 \leq 18$
4.  $x_1, x_2 \geq 0$


### Solution: Simplex Iteration: Basic Feasible Solution (BFS)

**Basis Selection:** The basis is defined as $B = (x_2, x_4, x_5)$, where:
* $x_2$: Decision variable 2
* $x_4$: Slack variable for Constraint 2
* $x_5$: Slack variable for Constraint 3

**Calculation:**
Using the basis matrix $B$ and the right-hand side vector $b$:
$$x_B = B^{-1}b$$

**Basic Feasible Solution:**
Substituting the values calculated in the Python implementation, the BFS vector $(x_1, x_2, x_3, x_4, x_5)$ is:
$$\mathbf{x} = [0, 3, 0, 2, 15]$$

* **Non-basic variables** ($x_1, x_3$) are set to $0$.
* **Basic variables** take the values: $x_2 = 3, x_4 = 2, x_5 = 15$.

In [127]:
import numpy as np

### 1. First Pass:

In [128]:
a_b = np.array([[1,0,0],
                [2,1,0],
                [1,0,1]])


In [129]:
a_n = np.array([[-1,1],
                [-1,0],
                [3,0]])

In [130]:
# column vectors
b = np.array([3,8,18]).T
c_b = np.array([3,0,0]).T
c_n = np.array([1,0]).T

In [131]:
# current BFS
x_b = np.linalg.inv(a_b) @ b
print(x_b)

[ 3.  2. 15.]


In [132]:
# Reduced costs
cn_T_bar = c_b.T @ np.linalg.inv(a_b) @ a_n - c_n.T
print(cn_T_bar)

[-4.  3.]


In [133]:
# RHS
RHS = np.linalg.inv(a_b) @ b
print(RHS)

[ 3.  2. 15.]


In [134]:
# Pivot column
pivot = np.linalg.inv(a_b) @ a_n[:,0] # select the first column
print(pivot)

[-1.  1.  4.]


### 2. Second Pass

From the first pass, x4 should be removed, and x1 should enter. Now the basic variables are (x1, x2, x5)

In [135]:
a_b = np.array([[-1,1,0],
                [-1,2,0],
                [3,1,1]])

In [136]:
a_n = np.array([[1,0],
                [0,1],
                [0,0]])

In [137]:
# column vectors
b = np.array([3,8,18]).T
c_b = np.array([1,3,0]).T
c_n = np.array([0,0]).T

In [138]:
# current BFS
x_b = np.linalg.inv(a_b) @ b
print(x_b)

[2. 5. 7.]


In [139]:
# Reduced costs
cn_T_bar = c_b.T @ np.linalg.inv(a_b) @ a_n - c_n.T
print(cn_T_bar)

[-5.  4.]


In [140]:
# RHS
RHS = np.linalg.inv(a_b) @ b
print(RHS)

[2. 5. 7.]


In [141]:
# Pivot column
pivot = np.linalg.inv(a_b) @ a_n[:,0] # select the first column
print(pivot)

[-2. -1.  7.]


3. Third Pass

From the first pass, x5 should be removed, and x3 should enter. Now the basic variables are (x1, x2, x3)

In [142]:
a_b = np.array([[-1,1,1],
                [-1,2,0],
                [3,1,0]])

In [143]:
a_n = np.array([[0,0],
                [1,0],
                [0,1]])

In [144]:
# column vectors
b = np.array([3,8,18]).T
c_b = np.array([1,3,0]).T
c_n = np.array([0,0]).T

In [145]:
# current BFS
x_b = np.linalg.inv(a_b) @ b
print(x_b)

[4. 6. 1.]


In [146]:
# Reduced costs
cn_T_bar = c_b.T @ np.linalg.inv(a_b) @ a_n - c_n.T
print(cn_T_bar)

[1.14285714 0.71428571]


In [147]:
# RHS
RHS = np.linalg.inv(a_b) @ b
print(RHS)

[4. 6. 1.]


The reduced costs are all positive, and we get the optimal solution (4, 6, 1) for the basic variables, and zeros for the non-basic variables.